---
  - name: add nginx vhost
    template: src=templates/vhost-redirect.j2 dest=/etc/nginx/sites-available/{{ hostname }}
    notify:
      - restart nginx
  - name: link nginx vhost in sites-enabled
    action: file src=/etc/nginx/sites-available/{{ hostname }} dest=/etc/nginx/sites-enabled/{{ hostname }} state=link
    notify:
      - reload nginx
