---
   user: www-data
   worker_processes: "{{ ansible_processor_vcpus }}"
   pid: /var/run/nginx.pid
   worker_connections: 768
   urlkey: http://nginx.org/keys/nginx_signing.key
   distro: "{{ ansible_distribution_release }}"
   nginxversion: 1.14.1-1~xenial
   hostname: test5.com 
   vhost: http://localhost:8081
